export const TIMER_CONSTANTS = {
  TOTAL_TIME: 600000,
  DIGIT_WIDTH_WITH_SPACING: 4,
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  CURSOR_BLINK_THRESHOLD: 440,
  POSITION: {
    X: 0,
    Y: 0,
    SPACING: 2,
    COLON_OFFSET: 8,
    LABEL_OFFSET: 3,
  },
  UPDATE_INTERVAL: 10,
} as const;